# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitAuthorRefresher < Formula
  desc ""
  homepage "https://github.com/pkarpovich/commit-author-refresher"
  version "1.0.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.0.0/commit-author-refresher_1.0.0_darwin_arm64.tar.gz"
      sha256 "b10fb56d0cf1bf86a854de95d36a28eab0c4dedd81f227e358e98947d623070b"

      def install
        bin.install "commit-author-refresher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.0.0/commit-author-refresher_1.0.0_darwin_amd64.tar.gz"
      sha256 "277a18bc6c86d70aa97671c344df6fab42052bf1d0649b349da7374aabd8dbf8"

      def install
        bin.install "commit-author-refresher"
      end
    end
  end
end
