# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitAuthorRefresher < Formula
  desc ""
  homepage "https://github.com/pkarpovich/commit-author-refresher"
  version "1.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.0.1/commit-author-refresher_1.0.1_darwin_amd64.tar.gz"
      sha256 "481ece7a6cde73f232d13c249d2a1d10abafcab877a624e10a4f05b70c162404"

      def install
        bin.install "commit-author-refresher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.0.1/commit-author-refresher_1.0.1_darwin_arm64.tar.gz"
      sha256 "87931ff793c76655f0100ae8a0b3526a30ebeda4cac0cb0d143aba4ff6b8463d"

      def install
        bin.install "commit-author-refresher"
      end
    end
  end
end
