# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShortcutsRemoteServer < Formula
  desc ""
  homepage "https://github.com/pkarpovich/shortcuts-remote-server"
  version "1.0.1"

  on_macos do
    url "https://github.com/pkarpovich/shortcuts-remote-server/releases/download/v1.0.1/shortcuts-remote-server_1.0.1_darwin_amd64.tar.gz"
    sha256 "ed0f81be0af5063f2999e730ac3c58b63f2561bd3773b7b017100e1453544c9a"

    def install
      bin.install "shortcuts-remote-server"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ShortcutsRemoteServer
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pkarpovich/shortcuts-remote-server/releases/download/v1.0.1/shortcuts-remote-server_1.0.1_linux_armv6.tar.gz"
      sha256 "b855f629c99dc2121d80f357a6d82dcb91f3e4417f29ffa2759487b66334df60"

      def install
        bin.install "shortcuts-remote-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pkarpovich/shortcuts-remote-server/releases/download/v1.0.1/shortcuts-remote-server_1.0.1_linux_amd64.tar.gz"
      sha256 "d71aaf211cdf59dc82cb6c7e255acfab57178ce52a205fe31854ff8845264103"

      def install
        bin.install "shortcuts-remote-server"
      end
    end
  end
end
