# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShortcutsRemoteServer < Formula
  desc ""
  homepage "https://github.com/pkarpovich/shortcuts-remote-server"
  version "1.1.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pkarpovich/shortcuts-remote-server/releases/download/v1.1.0/shortcuts-remote-server_1.1.0_darwin_arm64.tar.gz"
      sha256 "02de1d1dba8f25a54a23f7ff6192e63c484f091f150ee416db5b55d4fbb3039c"

      def install
        bin.install "shortcuts-remote-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pkarpovich/shortcuts-remote-server/releases/download/v1.1.0/shortcuts-remote-server_1.1.0_darwin_amd64.tar.gz"
      sha256 "d589582dae48472d3a9e0e06d5cbdd90af812638905e9552ad864b91a98a0358"

      def install
        bin.install "shortcuts-remote-server"
      end
    end
  end
end
