# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TurtleHarbor < Formula
  desc "Script manager daemon for macOS"
  homepage "https://github.com/pkarpovich/turtle-harbor"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pkarpovich/turtle-harbor/releases/download/v0.1.1/turtle-harbor_0.1.1_darwin_amd64.tar.gz"
    sha256 "e29ef6006b83ae6553507a76ff2325cd24e2b4ee4ba5016e14c28e391bbde019"

    def install
      bin.install "th"
      bin.install "turtled"
      (var/"lib/turtle-harbor").mkpath
      (var/"log/turtle-harbor").mkpath
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pkarpovich/turtle-harbor/releases/download/v0.1.1/turtle-harbor_0.1.1_darwin_arm64.tar.gz"
    sha256 "56caef462948d4173a048f2ad9ef7d0b58aae4d3e91bccaad62fe16fad037044"

    def install
      bin.install "th"
      bin.install "turtled"
      (var/"lib/turtle-harbor").mkpath
      (var/"log/turtle-harbor").mkpath
    end
  end

  service do
    run [opt_bin/"turtled"]
    keep_alive true
    working_dir var/"lib/turtle-harbor"
    log_path var/"log/turtle-harbor/daemon.log"
    error_log_path var/"log/turtle-harbor/daemon.error.log"
  end
end
