# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yafetch < Formula
  desc "Yet another neofetch"
  homepage "https://github.com/pkarpovich/yafetch"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pkarpovich/yafetch/releases/download/v0.1.0/yafetch_0.1.0_darwin_amd64.tar.gz"
    sha256 "e9b371f181da2a929173c5455654b660b60b300d8d8b5e6c00b1dc521eb3ac9c"

    def install
      bin.install "yafetch"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pkarpovich/yafetch/releases/download/v0.1.0/yafetch_0.1.0_darwin_arm64.tar.gz"
    sha256 "0587b27d4d862146a35d26b938bb3e75c28c6cf9979e41bb7c6e83b8a8d6d99e"

    def install
      bin.install "yafetch"
    end
  end
end
