# This file was generated by GoReleaser. DO NOT EDIT.
cask "yafetch" do
  desc "Yet another neofetch"
  homepage "https://github.com/pkarpovich/yafetch"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yafetch"

  on_macos do
    on_arm do
      url "https://github.com/pkarpovich/yafetch/releases/download/v0.2.0/yafetch_0.2.0_darwin_arm64.tar.gz"
      sha256 "90e935dbfada0698f35ef4bb560f91c2b36b22f4ba88a3d49b85f13136408b52"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yafetch"]
    end
  end

  # No zap stanza required
end
