# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitAuthorRefresher < Formula
  desc "Refreshes commit author in git history"
  homepage "https://github.com/pkarpovich/commit-author-refresher"
  version "1.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.1.2/commit-author-refresher_1.1.2_darwin_amd64.tar.gz"
    sha256 "bc354aecd85e57be0e7feb47c9c99df89e953565ccf9c20779e8480937b90edf"

    def install
      bin.install "commit-author-refresher"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/pkarpovich/commit-author-refresher/releases/download/v1.1.2/commit-author-refresher_1.1.2_darwin_arm64.tar.gz"
    sha256 "a99e7833d5173e3a8f1b2c7362128526f80dcc14de758647d43cac87515c5b5a"

    def install
      bin.install "commit-author-refresher"
    end
  end
end
